import type {
  Baby,
  Booking,
  BookingAssignment,
  Customer,
  Therapist,
  TherapistSchedule,
  Treatment,
  TreatmentPackage,
} from "@/modules/baby-spa/types";

const timestamp = "2026-08-10T08:00:00.000Z";

export const treatments: Treatment[] = [
  {
    id: "treatment-baby-massage",
    slug: "baby-massage",
    name: "Baby Massage",
    description: "Pijat lembut untuk membantu relaksasi, kualitas tidur, dan kenyamanan bayi.",
    durationMinutes: 45,
    price: 80000,
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1200&q=80",
    active: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "treatment-baby-swim",
    slug: "baby-swim",
    name: "Baby Swim",
    description: "Sesi berenang bayi dengan pendampingan terapis untuk stimulasi motorik.",
    durationMinutes: 30,
    price: 90000,
    image: "https://images.unsplash.com/photo-1543342384-1f1350e27861?auto=format&fit=crop&w=1200&q=80",
    active: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "treatment-baby-gym",
    slug: "baby-gym",
    name: "Baby Gym",
    description: "Aktivitas gerak ringan yang dirancang untuk koordinasi dan kekuatan bayi.",
    durationMinutes: 15,
    price: 45000,
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1200&q=80",
    active: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "treatment-baby-grooming",
    slug: "baby-haircut-grooming",
    name: "Baby Haircut / Grooming",
    description: "Perawatan grooming bayi yang higienis, rapi, dan nyaman.",
    durationMinutes: 30,
    price: 70000,
    image: "https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?auto=format&fit=crop&w=1200&q=80",
    active: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "treatment-mom-baby-relaxation",
    slug: "mom-baby-relaxation",
    name: "Mom & Baby Relaxation",
    description: "Sesi relaksasi singkat untuk ibu dan bayi setelah rangkaian treatment.",
    durationMinutes: 60,
    price: 130000,
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=1200&q=80",
    active: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const packages: TreatmentPackage[] = [
  {
    id: "package-happy-baby",
    slug: "happy-baby-package",
    name: "Happy Baby Package",
    description: "Paket single visit lengkap untuk stimulasi, berenang, dan relaksasi bayi.",
    price: 175000,
    image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?auto=format&fit=crop&w=1200&q=80",
    active: true,
    createdAt: timestamp,
    updatedAt: timestamp,
    items: [
      { id: "pkg-happy-1", packageId: "package-happy-baby", treatmentId: "treatment-baby-gym", sequence: 1, quantity: 1 },
      { id: "pkg-happy-2", packageId: "package-happy-baby", treatmentId: "treatment-baby-swim", sequence: 2, quantity: 1 },
      { id: "pkg-happy-3", packageId: "package-happy-baby", treatmentId: "treatment-baby-massage", sequence: 3, quantity: 1 },
    ],
  },
  {
    id: "package-calm-sleep",
    slug: "calm-sleep-package",
    name: "Calm Sleep Package",
    description: "Kombinasi massage dan relaksasi untuk membantu bayi lebih tenang.",
    price: 150000,
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=1200&q=80",
    active: true,
    createdAt: timestamp,
    updatedAt: timestamp,
    items: [
      { id: "pkg-calm-1", packageId: "package-calm-sleep", treatmentId: "treatment-baby-massage", sequence: 1, quantity: 1 },
      { id: "pkg-calm-2", packageId: "package-calm-sleep", treatmentId: "treatment-mom-baby-relaxation", sequence: 2, quantity: 1 },
    ],
  },
  {
    id: "package-first-spa",
    slug: "first-spa-package",
    name: "First Spa Package",
    description: "Pilihan ringan untuk kunjungan pertama dengan swim dan grooming.",
    price: 140000,
    image: "https://images.unsplash.com/photo-1492725764893-90b379c2b6e7?auto=format&fit=crop&w=1200&q=80",
    active: true,
    createdAt: timestamp,
    updatedAt: timestamp,
    items: [
      { id: "pkg-first-1", packageId: "package-first-spa", treatmentId: "treatment-baby-swim", sequence: 1, quantity: 1 },
      { id: "pkg-first-2", packageId: "package-first-spa", treatmentId: "treatment-baby-grooming", sequence: 2, quantity: 1 },
    ],
  },
];

export const customers: Customer[] = [
  { id: "customer-nadia", name: "Nadia Pratama", phone: "+628121110001", email: "nadia@example.com", createdAt: timestamp },
  { id: "customer-rani", name: "Rani Amelia", phone: "+628121110002", email: "rani@example.com", createdAt: timestamp },
  { id: "customer-putri", name: "Putri Maharani", phone: "+628121110003", email: "putri@example.com", createdAt: timestamp },
  { id: "customer-dinda", name: "Dinda Saputri", phone: "+628121110004", email: "dinda@example.com", createdAt: timestamp },
  { id: "customer-salsa", name: "Salsabila Rahma", phone: "+628121110005", email: "salsa@example.com", createdAt: timestamp },
];

export const babies: Baby[] = [
  { id: "baby-aisyah", customerId: "customer-nadia", name: "Aisyah", birthDate: "2025-02-14", gender: "FEMALE", notes: "Suka sesi air hangat.", createdAt: timestamp, updatedAt: timestamp },
  { id: "baby-rafa", customerId: "customer-nadia", name: "Rafa", birthDate: "2024-12-03", gender: "MALE", notes: "Butuh adaptasi pelan.", createdAt: timestamp, updatedAt: timestamp },
  { id: "baby-naira", customerId: "customer-rani", name: "Naira", birthDate: "2025-05-20", gender: "FEMALE", notes: "Tidur siang pukul 12.", createdAt: timestamp, updatedAt: timestamp },
  { id: "baby-alika", customerId: "customer-putri", name: "Alika", birthDate: "2025-01-08", gender: "FEMALE", notes: "Senang dipijat lembut.", createdAt: timestamp, updatedAt: timestamp },
  { id: "baby-bima", customerId: "customer-dinda", name: "Bima", birthDate: "2024-10-19", gender: "MALE", notes: "Aktif saat baby gym.", createdAt: timestamp, updatedAt: timestamp },
  { id: "baby-kirana", customerId: "customer-salsa", name: "Kirana", birthDate: "2025-03-25", gender: "FEMALE", notes: "Sensitif dengan ruangan dingin.", createdAt: timestamp, updatedAt: timestamp },
  { id: "baby-ammar", customerId: "customer-rani", name: "Ammar", birthDate: "2024-09-11", gender: "MALE", notes: "Cocok sesi pagi.", createdAt: timestamp, updatedAt: timestamp },
];

export const therapists: Therapist[] = [
  { id: "therapist-siti", name: "Siti Rahma", phone: "+628221110001", photo: "", active: true, notes: "Spesialis massage dan baby gym.", createdAt: timestamp, updatedAt: timestamp },
  { id: "therapist-rina", name: "Rina Putri", phone: "+628221110002", photo: "", active: true, notes: "Berpengalaman untuk baby swim.", createdAt: timestamp, updatedAt: timestamp },
  { id: "therapist-dewi", name: "Dewi Lestari", phone: "+628221110003", photo: "", active: true, notes: "Ada konflik jadwal demo.", createdAt: timestamp, updatedAt: timestamp },
  { id: "therapist-ayu", name: "Ayu Maharani", phone: "+628221110004", photo: "", active: true, notes: "Shift siang.", createdAt: timestamp, updatedAt: timestamp },
  { id: "therapist-fitri", name: "Fitri Nuraini", phone: "+628221110005", photo: "", active: false, notes: "Tidak aktif sementara.", createdAt: timestamp, updatedAt: timestamp },
];

export const therapistSchedules: TherapistSchedule[] = therapists.map((therapist) => ({
  id: `schedule-${therapist.id}`,
  therapistId: therapist.id,
  dayOfWeek: 3,
  startTime: therapist.id === "therapist-ayu" ? "12:00" : "08:00",
  endTime: therapist.id === "therapist-rina" ? "16:00" : "12:00",
  active: therapist.active,
}));

export const bookings: Booking[] = [
  {
    id: "booking-demo",
    bookingNumber: "BS-20260812-001",
    customerId: "customer-nadia",
    babyId: "baby-aisyah",
    bookingType: "PACKAGE",
    packageId: "package-happy-baby",
    bookingDate: "2026-08-12",
    startTime: "10:00",
    endTime: "11:30",
    durationMinutes: 90,
    status: "PENDING",
    customerNotes: "Aisyah agak sensitif dengan air terlalu dingin.",
    adminNotes: "",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "booking-conflict",
    bookingNumber: "BS-000119",
    customerId: "customer-rani",
    babyId: "baby-naira",
    bookingType: "TREATMENT",
    treatmentId: "treatment-baby-massage",
    bookingDate: "2026-08-12",
    startTime: "09:30",
    endTime: "11:00",
    durationMinutes: 90,
    status: "CONFIRMED",
    customerNotes: "Mulai dari massage ringan.",
    adminNotes: "Jadwal konflik untuk demo availability.",
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  { id: "booking-002", bookingNumber: "BS-000120", customerId: "customer-nadia", babyId: "baby-rafa", bookingType: "TREATMENT", treatmentId: "treatment-baby-massage", bookingDate: "2026-08-12", startTime: "13:30", endTime: "14:15", durationMinutes: 45, status: "CONFIRMED", customerNotes: "Rafa perlu waktu adaptasi.", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-003", bookingNumber: "BS-000121", customerId: "customer-putri", babyId: "baby-alika", bookingType: "PACKAGE", packageId: "package-first-spa", bookingDate: "2026-08-10", startTime: "09:00", endTime: "10:00", durationMinutes: 60, status: "COMPLETED", customerNotes: "Kunjungan pertama.", adminNotes: "Selesai lancar.", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-004", bookingNumber: "BS-000122", customerId: "customer-dinda", babyId: "baby-bima", bookingType: "TREATMENT", treatmentId: "treatment-baby-gym", bookingDate: "2026-08-10", startTime: "11:00", endTime: "11:15", durationMinutes: 15, status: "COMPLETED", customerNotes: "", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-005", bookingNumber: "BS-000123", customerId: "customer-salsa", babyId: "baby-kirana", bookingType: "PACKAGE", packageId: "package-calm-sleep", bookingDate: "2026-08-11", startTime: "10:00", endTime: "11:45", durationMinutes: 105, status: "CONFIRMED", customerNotes: "Ruangan jangan terlalu dingin.", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-006", bookingNumber: "BS-000124", customerId: "customer-rani", babyId: "baby-ammar", bookingType: "TREATMENT", treatmentId: "treatment-baby-swim", bookingDate: "2026-08-13", startTime: "09:00", endTime: "09:30", durationMinutes: 30, status: "PENDING", customerNotes: "Sesi pagi.", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-007", bookingNumber: "BS-000125", customerId: "customer-putri", babyId: "baby-alika", bookingType: "TREATMENT", treatmentId: "treatment-baby-grooming", bookingDate: "2026-08-13", startTime: "14:00", endTime: "14:30", durationMinutes: 30, status: "CANCELLED", customerNotes: "", adminNotes: "Customer reschedule.", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-008", bookingNumber: "BS-000126", customerId: "customer-dinda", babyId: "baby-bima", bookingType: "PACKAGE", packageId: "package-happy-baby", bookingDate: "2026-08-14", startTime: "10:00", endTime: "11:30", durationMinutes: 90, status: "PENDING", customerNotes: "Mohon slot pagi.", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-009", bookingNumber: "BS-000127", customerId: "customer-salsa", babyId: "baby-kirana", bookingType: "TREATMENT", treatmentId: "treatment-mom-baby-relaxation", bookingDate: "2026-08-15", startTime: "15:00", endTime: "16:00", durationMinutes: 60, status: "CONFIRMED", customerNotes: "", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-010", bookingNumber: "BS-000128", customerId: "customer-rani", babyId: "baby-naira", bookingType: "TREATMENT", treatmentId: "treatment-baby-massage", bookingDate: "2026-08-08", startTime: "10:00", endTime: "10:45", durationMinutes: 45, status: "COMPLETED", customerNotes: "", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-011", bookingNumber: "BS-000129", customerId: "customer-nadia", babyId: "baby-aisyah", bookingType: "PACKAGE", packageId: "package-happy-baby", bookingDate: "2026-08-05", startTime: "10:00", endTime: "11:30", durationMinutes: 90, status: "COMPLETED", customerNotes: "", adminNotes: "Treatment selesai.", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-012", bookingNumber: "BS-000130", customerId: "customer-putri", babyId: "baby-alika", bookingType: "TREATMENT", treatmentId: "treatment-baby-swim", bookingDate: "2026-08-07", startTime: "13:00", endTime: "13:30", durationMinutes: 30, status: "COMPLETED", customerNotes: "", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-013", bookingNumber: "BS-000131", customerId: "customer-dinda", babyId: "baby-bima", bookingType: "TREATMENT", treatmentId: "treatment-baby-massage", bookingDate: "2026-08-16", startTime: "10:30", endTime: "11:15", durationMinutes: 45, status: "NO_SHOW", customerNotes: "", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-014", bookingNumber: "BS-000132", customerId: "customer-salsa", babyId: "baby-kirana", bookingType: "PACKAGE", packageId: "package-first-spa", bookingDate: "2026-08-17", startTime: "09:30", endTime: "10:30", durationMinutes: 60, status: "PENDING", customerNotes: "Cek suhu air dulu.", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
  { id: "booking-015", bookingNumber: "BS-000133", customerId: "customer-rani", babyId: "baby-ammar", bookingType: "TREATMENT", treatmentId: "treatment-baby-gym", bookingDate: "2026-08-18", startTime: "11:00", endTime: "11:15", durationMinutes: 15, status: "CONFIRMED", customerNotes: "", adminNotes: "", createdAt: timestamp, updatedAt: timestamp },
];

export const assignments: BookingAssignment[] = [
  { id: "assignment-conflict", bookingId: "booking-conflict", therapistId: "therapist-dewi", status: "ASSIGNED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-002", bookingId: "booking-002", therapistId: "therapist-siti", status: "ASSIGNED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-003", bookingId: "booking-003", therapistId: "therapist-rina", status: "COMPLETED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-004", bookingId: "booking-004", therapistId: "therapist-ayu", status: "COMPLETED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-005", bookingId: "booking-005", therapistId: "therapist-rina", status: "ASSIGNED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-009", bookingId: "booking-009", therapistId: "therapist-ayu", status: "ASSIGNED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-010", bookingId: "booking-010", therapistId: "therapist-siti", status: "COMPLETED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-011", bookingId: "booking-011", therapistId: "therapist-siti", status: "COMPLETED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-012", bookingId: "booking-012", therapistId: "therapist-siti", status: "COMPLETED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
  { id: "assignment-015", bookingId: "booking-015", therapistId: "therapist-rina", status: "ASSIGNED", assignedBy: "admin-demo", assignedAt: timestamp, createdAt: timestamp, updatedAt: timestamp },
];
